//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyVersionAttribute("0.6.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.6.0-alpha")]

// Generated by the MSBuild WriteCodeFragment class on 7/25/2013 4:08:10 AM.

