//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyVersionAttribute("0.13.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.13.2")]

// Generated by the MSBuild WriteCodeFragment class on 2/24/2015 8:00:50 PM.

