//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.35312
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyVersionAttribute("0.10.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.10.2")]

// Von der MSBuild WriteCodeFragment-Klasse für 09.11.2014 13:27:16 generiert.

